name: "Branch protection"
on:
  pull_request:
    types: [opened, edited, reopened, synchronize]
  
jobs:
  test_job:
    runs-on: ubuntu-latest
    name: Branch naming protection check.
    steps:
      - uses: knawat/github-actions-gitflow@v1
