name: Copy Markdown to Stoplight Branch

on:
  push:
    branches: [main]

jobs:
  copy-markdown:
    name: Deploy Stoplight documentation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Check for Stoplight Branch
        run: |
          git checkout -b stoplight_docs --force
          git push origin stoplight_docs --force
      - name: Removing all files except Markdown Files
        run: |
          find . -mindepth 1 -type f ! -name "*.md" -delete 
          find . -mindepth 1 -type d -exec rm -rf {} +
      - name: Commit Changes
        run: |
          git add .
          git commit -m "Update Stoplight documentation"
          git push origin stoplight_docs
