# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: SPM Build and Test 

on:
  push:
    branches: [ "feature/unit-test", "main", "release/1.0.3", "release/1.0.4"]
  pull_request:
    branches: [ "feature/unit-test", "main", "release/1.0.3", "release/1.0.4" ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build and run tests
      run: xcodebuild test -scheme PlaybackSDK -destination 'platform=iOS Simulator,name=iPhone 13'
